# -*- coding: utf-8 -*-
"""Brain MRI AI Diagnostic Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ktcm85nF65N1VhykpQYWIwqlrAut1g43
"""

pip install gradio pillow

import gradio as gr
from PIL import Image
import hashlib

def classify_tumor_type(image):
    image_bytes = image.tobytes()
    digest = hashlib.md5(image_bytes).hexdigest()
    val = int(digest, 16) % 4
    return ["Glioma", "Meningioma", "Pituitary Tumor", "No Tumor"][val]

def generate_mri_report(image, name, age, gender):
    tumor_type = classify_tumor_type(image)

    base_findings = f"""
🧠 AI-Generated MRI Diagnosis Report
---------------------------------------
Patient Information:
Name: {name}
Age: {age}
Gender: {gender}

Findings:
Tumor Classification: {tumor_type}
"""

    if tumor_type == "No Tumor":
        findings = base_findings + """
No abnormal mass or enhancement is identified on the MRI. Brain parenchyma appears normal in signal intensity and morphology.
No midline shift or compression of adjacent structures.
No signs of edema or mass effect.
"""
        risk = "Risk Assessment:\nNo evidence of tumor. Malignancy risk is [Low (0/100)]."
        treatment = "- No treatment necessary. Routine follow-up only if clinically indicated."
    else:
        if tumor_type == "Glioma":
            location = "Right frontal lobe"
            extent = "4.5 cm"
            malignancy = "[High (70/100)]"
            treatment_options = """
- Surgical Resection: Primary treatment depending on resectability.
- Radiation Therapy: As adjunct or standalone based on tumor grade.
- Clinical Trials: May be considered.
"""
        elif tumor_type == "Meningioma":
            location = "Left parietal lobe"
            extent = "3.2 cm"
            malignancy = "[Medium (50/100)]"
            treatment_options = """
- Observation: If asymptomatic and stable.
- Surgical Resection: If symptomatic or growing.
- Radiation Therapy: Post-op or as alternative.
"""
        elif tumor_type == "Pituitary Tumor":
            location = "Sellar region"
            extent = "1.8 cm"
            malignancy = "[Low to Medium (40/100)]"
            treatment_options = """
- Endocrine evaluation required.
- Surgery: If causing hormonal dysfunction or compression.
- Surveillance MRI: For small, stable tumors.
"""

        findings += f"""
Location: {location}
Size/Extent: {extent}
Type: Hyperintense on T2-weighted imaging with post-contrast enhancement
Mass Effect: Mild perilesional edema with no major midline shift
"""
        risk = f"""
Risk Assessment:
Based on the MRI findings, the risk of malignancy is estimated to be {malignancy}.
"""
        treatment = f"""
Treatment Recommendations:
Based on the diagnosis, the following options are considered:
{treatment_options}
"""

    follow_up = "Follow-up Schedule:\nMRI follow-up in 1–3 months depending on tumor type and patient symptoms."

    return findings + "\n" + risk + "\n" + treatment + "\n" + follow_up

# Gradio app
demo = gr.Interface(
    fn=generate_mri_report,
    inputs=[
        gr.Image(type="pil", label="Upload Brain MRI Image"),
        gr.Textbox(label="Patient Name"),
        gr.Number(label="Age"),
        gr.Radio(choices=["Male", "Female", "Other"], label="Gender")
    ],
    outputs=gr.Textbox(lines=40, label="AI-Generated MRI Report"),
    title="Brain MRI AI Diagnostic Assistant",
    description="Upload a brain MRI image and patient information to receive an AI-generated diagnosis report. This demo simulates tumor classification (glioma, meningioma, pituitary tumor, or no tumor)."
)

demo.launch(share=True)